### ISSUE TITLE
How to prepare dataset specially the table data cropbox xml files ?

### ISSUE THREAD

**Issue by jyotiyadav94** [AshishSalaskar1/TableNet_Implementation#2]

**Comment by AshishSalaskar1** [comment]
- The functions used for preparing data are `extract_col_mask` and `extract_table_mask` in this file : [TableNetEDA ](https://github.com/AshishSalaskar1/TableNet_Implementation/blob/main/TableNet_EDA.ipynb)

- The Neural Net expects the coordinates in the format `(Xmin, Xmax, Ymin, Ymax)`. So we need to get the coordinates in this format. 

- Another Link: https://stackoverflow.com/questions/52824584/do-anyone-know-how-to-extract-image-coordinate-from-marmot-dataset/53377650

**Comment by jyotiyadav94** [comment]
First of all thank you giving the clear views on the implementation part and also for the medium post. 
I wanted to ask you if I can create my own table XML file similar to table xml's created in marmot dataset and then utilize the extract_table_mask function to get the table mask and table bounding boxes ?

I am able to create the marmot dataset for column XML but I have trouble understanding the structure of the table XML's 
If possible could you please provide some info on that.

**Comment by AshishSalaskar1** [comment]
The Marmots dataset uses [Pascal VOOC format](https://www.section.io/engineering-education/understanding-pascal-voc-dataset/) to represent an image's bounding boxes. There are multiple tools that support manually annotating images into Pascal VOOC ( I have personally used **[labelImg](https://pypi.org/project/labelImg/)** before which supports saving annotations in Pascal VOOC Format. It will save your annotations into a XML file which can be used)

- You can manually annotate the tables and columns but make sure to keep the class name as `column` or `table` accordingly. Then the `extract_col_mask` function can be utilized by just checking the bounding box class label (column or table) and can be used to generate both column and table masks for an image

If you want to convert it automatically i.e you have the bounding boxes (for tables and columns ) in some other formats and want to convert them into PASCAL VOOC format, then maybe we would need to write a script to convert them and then utilize the functions to read the data.

**Comment by AshishSalaskar1** [comment]
Also, the original marmot's dataset(used to extract table masks) uses a [different XML format](https://roboflow.com/formats/marmot-xml) which is somewhat different. It uses Page/CropBox -> Composites -> BBox approach which is a bit hard to generate for new images. I haven't yet found any tool which supports exporting annotations in this particular format

So I guess the more feasible way seems to be to have both your table and column mask XMLs in Pascal VOOC format and then use  the `extract_col_masks` function with some modifications to generate both the column and table masks

**Comment by jyotiyadav94** [comment]
Thank you so much for the detailed explanation. I used a similar approach.

**Comment by atifayaz99** [comment]
where is column and table data? i downloaded the marmot's dataset, its shows me only positive. negative -> raw and labled folders no column and table xml files.
